// import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    //  justify-center items-center
    <div>
      <div className="box-border border-2 border-cyan-900 text-xs">
        <div className="p-2 bg-cyan-600 text-white">
          更新情報
        </div>
        <div className="p-2">
          2023年3月1日　
        「珠算第４３６回　暗算第５４７回　読上算第２５４回」検定合格者
        </div>
        <div className="p-2">
          2022年12月21日　
          「珠算第４３５回　暗算第５４５回　読上算第２５２回」検定合格者</div>
        <div className="p-2">
          2022年12月6日　
          「令和４年度検定のご案内」更新</div>
        <div className="p-2">
          2022年11月4日　
          「珠算第４３４回　暗算第５４３回　読上算第２５０回」検定合格者</div>
        <div className="p-2">
          2022年11月3日　
          「教養講習会（4年度）」更新</div>
      </div>
      <h1>公益社団法人群馬県珠算連盟の概要</h1>
      <div>
        群馬県珠算連盟は、昭和28年4月2日、群馬県珠算塾協会から大きな期待を受けて群馬県から念願の群馬県唯一の社団法人の許可を受け誕生しました。また平成２５年７月１日より公益社団法人に移行しました。
        現在約１００名の会員がおります。また、平成２５年７月１日に新公益法人に移行認可されました。
      </div>
      {/* // className="flex justify-center" */}
      <Image src="/images/IMG_2314.jpg"
          alt="menu"
          width={300} height={10}
          className="mx-auto m-2"
        ></Image>
      <Image src="/images/renmei1.jpg"
          alt="menu"
          width={300} height={10}
          className="mx-auto m-2"
        ></Image>
    </div>
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </h1>

    //     <p className={styles.description}>
    //       Get started by editing{' '}
    //       <code className={styles.code}>pages/index.js</code>
    //     </p>

    //     <div className={styles.grid}>
    //       <a href="https://nextjs.org/docs" className={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>

    //       <a href="https://nextjs.org/learn" className={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>

    //       <a
    //         href="https://github.com/vercel/next.js/tree/canary/examples"
    //         className={styles.card}
    //       >
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //       >
    //         <h2>Deploy &rarr;</h2>
    //         <p>
    //           Instantly deploy your Next.js site to a public URL with Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{' '}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
  )
}
